co = coroutine.create(function() 
	print("Printing from inside the coroutine co for the first time.")
	coroutine.yield()
	print("Printing from inside the coroutine co for the second time.")
end)
print("Printing from outside the coroutine for the first time.")
coroutine.resume(co)
print("Printing from outside the coroutine for the second time.")
coroutine.resume(co)
print(coroutine.status(co))
